CREATE TABLE test(
	Id INTEGER,
	LotArea	Utilities INTEGER,	
	LotConfig INTEGER,	
	Neighborhood VARCHAR,	
	Condition1 VARCHAR,
	Condition2 VARCHAR,	
	BldgType VARCHAR,	
	HouseStyle VARCHAR,	
	OverallQual INTEGER,	
	OverallCond INTEGER,
	YearBuilt INTEGER,	
	YearRemodAdd INTEGER,	
	RoofMatl VARCHAR,	
	Exterior1st VARCHAR,	
	Exterior2nd VARCHAR,
	MasVnrArea DOUBLE PRECISION,
	ExterQual VARCHAR,	
	ExterCond VARCHAR,	
	Foundation VARCHAR,	
	BsmtFinType2 VARCHAR,	
	GrLivArea INTEGER,	
	BsmtFullBath DOUBLE PRECISION,	
	BsmtHalfBath DOUBLE PRECISION,	
	FullBath INTEGER,	
	HalfBath INTEGER,	
	BedroomAbvGr INTEGER,	
	KitchenQual VARCHAR,	
	Functional VARCHAR,	
	Fireplaces VARCHAR,	
	FireplaceQu VARCHAR,	
	GarageType VARCHAR,	
	GarageArea DOUBLE PRECISION,	
	GarageCond TEXT,	
	PavedDrive TEXT,	
	MoSold INTEGER,	
	YrSold INTEGER,	
	SaleType VARCHAR,	
	SaleCondition VARCHAR
);

CREATE TABLE train(
	Id INTEGER,
	LotArea	Utilities INTEGER,	
	LotConfig INTEGER,	
	Neighborhood VARCHAR,	
	Condition1 VARCHAR,
	Condition2 VARCHAR,	
	BldgType VARCHAR,	
	HouseStyle VARCHAR,	
	OverallQual INTEGER,	
	OverallCond INTEGER,
	YearBuilt INTEGER,	
	YearRemodAdd INTEGER,	
	RoofMatl VARCHAR,	
	Exterior1st VARCHAR,	
	Exterior2nd VARCHAR,
	MasVnrArea DOUBLE PRECISION,
	ExterQual VARCHAR,	
	ExterCond VARCHAR,	
	Foundation VARCHAR,	
	BsmtFinType2 VARCHAR,	
	GrLivArea INTEGER,	
	BsmtFullBath DOUBLE PRECISION,	
	BsmtHalfBath DOUBLE PRECISION,	
	FullBath INTEGER,	
	HalfBath INTEGER,	
	BedroomAbvGr INTEGER,	
	KitchenQual VARCHAR,	
	Functional VARCHAR,	
	Fireplaces VARCHAR,	
	FireplaceQu VARCHAR,	
	GarageType VARCHAR,	
	GarageArea DOUBLE PRECISION,	
	GarageCond TEXT,	
	PavedDrive TEXT,	
	MoSold INTEGER,	
	YrSold INTEGER,	
	SaleType VARCHAR,	
	SaleCondition VARCHAR,
	SalePrice VARCHAR
);